### ISSUE TITLE
Cross-platform post-mortem debugging tools

### ISSUE THREAD

**Issue by misterdjules** [nodejs/post-mortem#10] opened 2015-10-05 17:59 UTC
This issue was created from https://github.com/nodejs/node/issues/2764. Here's the original issue description by @yunong:

Hi, at Netflix we leverage https://github.com/joyent/mdb_v8 quite heavily in production as the primary tool used to debug memory leaks and analyze production issues. It is currently, the only tool that we've had success with when it comes to fixing memory leaks in production. We are able to take a Linux Node 0.10-0.12 core dump, and debug it with mdb on Illumos. 

It looks like this facility no longer exists in 4.0.0. As it turns out -- this is rather unfortunate and is a blocker when it comes to moving our production Node deployments on to 4.0.0.

It looks like @tjfontaine has done the work sometime ago to migrate a subset of the functionality to LLDB here https://github.com/tjfontaine/lldb-v8 

If mdb_v8.so is going to be no longer kept up to date with Node, can we extend lldb-v8 to port over the rest of mdb_v8? This would ensure that this kind of critical post mortem analysis is available in new releases of node going forward and also more broadly on other platforms. Specifically, commands like `::findjsobjects`, `::jssource`, `::jssonconstructor` are critical to debugging our production stack. 

Just to be clear, there are no other tools that exist for Node today that can successfully debug memory leaks on production instances in the way that `mdb_v8` can.

cc @lucamaraschi @mikeal @indutny @davepacheco @misterdjules

**Comment by seabaylea** [comment] 2015-10-06 08:18
@misterdjules Have you tried/looked at IDDE? I'd be interested in you views on how IDDE and MDB compare.
http://www.ibm.com/developerworks/library/wa-ibm-node-enterprise-dump-debug-sdk-nodejs-trs/index.html

IDDE is limited to the "IBM" builds of Node.js because of the way it extracts the structure definition - something that we need to change. One of the areas I'd like to discuss is the best way to do that, ideally covering more than just the V8 structures (so beyond what's available from gen-postmorten-metadata.py), and being fully cross-platform (including more esoteric platforms like AIX and mainframes).

**Comment by lucamaraschi** [comment] 2015-10-06 12:18
@misterdjules regarding to what @seabaylea also mentioned, can we somehow plan an overview/documentation/architecture of how currently and ideally we see post-mortem implemented?I mean on a practical level (so technical) and operational.

This should also answer part of [#7](https://github.com/nodejs/post-mortem/issues/7). I am more interested on the software architecture and see how we can also explain how it works to more people.

**Comment by misterdjules** [comment] 2015-10-06 16:13
@seabaylea I've wanted to try IDDE for a while now, this meeting might be the perfect excuse :)

> One of the areas I'd like to discuss is the best way to do that, ideally covering more than just the V8 structures (so beyond what's available from gen-postmorten-metadata.py)

What other data did you have in mind, node-specific data structures? Can you give us some examples?

Also, I seem to remember that during the latest Node Summit conference you had talked about open sourcing at least parts of IDDE, do you know if some progress has been made on that front?

**Comment by misterdjules** [comment] 2015-10-06 16:20
@lucamaraschi OK, what would be the goal of such a document? You mention being able to explain to others how it works. You also mentioned a document that describes how post-mortem is implemented _currently_ and how it would be implemented _ideally_. It seems that describes three different documents. Maybe you could open a new issue to discuss that? Or if you think each document would have its own specific purpose, one issue per document?

Also, @davepacheco wrote some notes about [the design and implementation of mdb_v8](https://github.com/joyent/mdb_v8#design-and-implementation-notes).

**Comment by seabaylea** [comment] 2015-10-07 11:16
@misterdjules We should be able to extract all C structures from all of the components, not just the heap and stack/frame structures from V8. This would include handles and events from libuv, and lower level internal structures from V8.

We'd like to open source some/all of IDDE, but the blocker for us is the way that we do extract structs - we use a proprietary compiler at the moment to generate the data, which we have to move away from.

Has anyone looked at using DWARF/ELF data in the past?

**Comment by davepacheco** [comment] 2015-10-07 14:31
@seabaylea When we first looked at doing mdb_v8, I started with DWARF, but quickly found that there was no DWARF debugging information for the heap classes.  Because of the way V8 doesn't use normal C++ structure fields for heap classes, but rather use static integers that are used to generate accessors, the required offsets were compiled out even in debug mode, and the DWARF information reported only that these fields had once existed and were compiled out.  That's why we moved to the more ad-hoc approach that we did.  Admittedly, this was 2011, but I don't think any of this has changed.

As for the other native components (like V8 structures outside the heap and libuv), I would expect DWARF to work for those.  One question is whether it's tenable for people to use DWARF in production binaries?  Historically, we've converted DWARF to CTF at build time because CTF is much smaller.

**Comment by tjfontaine** [comment] 2015-10-07 15:46
I think there's discussion of two things:
1. Inspecting and debugging the V8 runtime of a target
2. Inspecting and debugging the Node.js "runtime" of a target, that depends on the former

As @davepacheco rightly points out, DWARF for Handles and their descendants is not particularly meaningful, and the time it takes to generate and the size of it on disk for that particularly complex C++ project really doesn't yield the kind of benefit you may be looking for. If what you're trying to do is debug V8 for V8 because you suspect V8 is causing your problem, then you may be more interested in that thing.

However, for most of the consumers of these tools they're usually more skeptical about their application logic (or a related module) than they are of the V8 runtime. So getting more information about how HandleScopes are constructed isn't as important as "Show me the difference between live objects (rooted in existing HandleScopes) and those objects which we can still find in the heap that are not live".

If the only/best way to solve that is with DWARF, then by all means "tally-ho", but I expect not.

On the subject of debugging the Node.js "runtime", which I'll further define as Node.js' C++ data structures and libuv's data structures, when last I left the v0.X series of Node.js the release builds included a libuv that was in fact built with DWARF (and was not intentionally stripped) [1]. In the past with mdb_v8 I was able to go from net.Socket to its handle and get the internal field that held the libuv structure and then dereference it as the actual libuv structure.

(At the time I wasn't able to do a direct DWARF -> CTF conversion though, because there would be multiple DIE's in the node binary, and the tooling wasn't able to deal with that scenario -- I think that has changed recently)

So knowingly or not, people are/were running with DWARF in production.

It's probably more valuable to have access to the internal structures of Node.js and libuv than it is to have access to the layouts of V8's data structures. But I think they are two different things. Tooling to introspect V8 pertains to a wider community than what is useful to the Node.js community (There's more to the [V8] world than Node.js and Chrome). And tooling to know "WTF is Node.js doing", which depends on the tooling to debug V8, but can interpret that into meaningful results (These are all your sockets, these are all your files, etc etc).

In lieu of the tooling from IBM finally being open sourced, there is a solution that works today, that is already open source, and ships in the source tree of V8 (gen-postmortem). No one is locked into only using the mdb_v8 solution, as evidenced by the start of my lldb-v8 plugin (which I will talk more about in a moment). If other tools need more information to be successful, or provide more in-depth information, then those things should be added to the script and upstreamed to V8.

Keeping it with V8 is the right place, the fact that it occasionally gets broken probably just means they need more tests to understand why their changes broke it, and then hopefully they'll help maintain in a more active way instead of it being the onus of the Node.js community (and mostly @davepacheco) to make it work again.

The tooling to know "WTF is Node.js doing" (from a target as opposed to live instrumentation) largely doesn't exist, and should be designed, but I think it only makes sense when first understanding how you cross the VM/Node.js barrier.

On the lldb-v8 front, I will happily reassign ownership of that module to whomever wants to finish/improve it. I did it as an example for NodeConfEU and it's the cumulative work of maybe 3 days, it's very immature, though it is a start of a thing. One thing I will note, while working with lldb I got really frustrated with how it works, mostly the fact that you can't actually do composable commands, so if you have two commands that you want to string together you must write a macro or another plugin that does that thing. This isn't unique to lldb, it applies to gdb as well, and probably others. As a result I took a step back and started to work on another project which allows me to first have an mdb like experience but using lldb. You can that work at https://github.com/tjfontaine/llmdb.

Let me know if I can be of further assistance, keep up the great work!

[1] https://github.com/nodejs/node-v0.x-archive/blob/v0.12/deps/uv/uv.gyp#L125

**Comment by alin00** [comment] 2015-10-07 18:02
I work for the same organization as @hhellyeribm and @seabaylea, but focusing on multi-language runtimes.

My (perhaps idealistic) hope would be to arrive at a portable open standard for formatting debug information. This would facilitate development of front-end debug tooling, like IDDE, that could be more easily extended to multiple languages. CTF might be a good basis for an open standard, or it might not. IDDE currently uses a different debug format.

How the debug information is generated should be handled as best suits each particular runtime. Scraping from DWARF is a good starting point for the C/C++ data structures in a runtime, but as others have pointed out, DWARF needs to be supplemented with additional tooling.

> One question is whether it's tenable for people to use DWARF in production binaries?

We currently generate DWARF for production binaries and strip it out prior to distribution.

**Comment by davepacheco** [comment] 2015-10-07 18:33
> My (perhaps idealistic) hope would be to arrive at a portable open standard for formatting debug information.

For V8 specifically, or for multiple languages?  I'm not sure how it would be possible to generalize debug metadata across different dynamic runtimes, but I'd be interested to hear ideas on this. V8's design choices (e.g., using tagged pointers, accessing everything through getters/setters, and not defining structure fields at all for heap object classes) essentially require that the debugger understand pretty low-level V8 details.  On top of that, there are many additional semantics that mdb_v8 (for example) essentially hardcodes, including:
- given an address representing a heap object (including small integers, represented inside the "address"), how do you identify what kind of object it is?
- given an address representing a small integer in particular, how do you extract the actual value?
- given an address representing a JavaScript object, how do you enumerate the property names and values?
- given an address representing a JavaScript function, how do you enumerate closed-over variables (both names and values)?

These are all algorithms, not data structures.  Implementing these for V8 essentially requires duplicating underlying V8 behavior (e.g., for property lookup), though it's often substantially simpler in the debugger because it doesn't have to handle every case and performance is not critical.  It's unfortunate that functionality is duplicated, but it's been an excellent tradeoff for us.  I'm not sure how best to generalize this.

Another approach that Bryan Cantrill and I discussed with some of the original members of the V8 team (that are now largely working on Dart) is to build this functionality into the official debugger.  That is, the VM itself would ship with a debugger that looks just like the normal debugger API, but would support reading its state from a core file.  This feels like the most promising way to a robust approach, but requires more a lot more interest from the V8 team than I've seen up to this point.

> > One question is whether it's tenable for people to use DWARF in production binaries?
> 
> We currently generate DWARF for production binaries and strip it out prior to distribution.

That data point suggests that it's not tenable.

**Comment by alin00** [comment] 2015-10-07 18:42
> > > One question is whether it's tenable for people to use DWARF in production binaries?
> > 
> > We currently generate DWARF for production binaries and strip it out prior to distribution.
> 
> That data point suggests that it's not tenable.

DWARF is an intermediate artifact in the generation of debug metadata.  It doesn't need to be installed on a production system or loaded into a running process.

**Comment by davepacheco** [comment] 2015-10-07 18:53
> DWARF is an intermediate artifact in the generation of debug metadata. It doesn't need to be installed on a production system or loaded into a running process.

As I understand it, if you don't have DWARF in the production binary, then you need a separate DWARF binary around when you debug a production core file.  Historically, we've found this too onerous a requirement for developers, both working on their own software and supporting customers who may have their own custom builds.  (This is actually why CTF was created -- to be able to keep the important parts of the DWARF debugging data inside production binaries so that it would be available in all core dumps without needing a separate debug binary around.  The V8-specific debug metadata that mdb_v8 uses is similarly lightweight and shipped in all of our binaries.)

**Comment by alin00** [comment] 2015-10-07 20:05
@davepacheco Apologies if it sounded like I was advocating using DWARF _instead of_ CTF. That was not my meaning. I absolutely agree that you need lighter-weight metadata inside production binaries.

Regarding generalizing debug metadata, this basic information seems runtime-agnostic:
- data structure info: names, sizes, and offsets of fields
- enumerated value info: symbolic and numeric values 

We can extract a lot of usefulness just from the above.

Some algorithms, like walking a hashtable or walking a stack, are operations we need for multiple languages, but we haven't figured out how to encode them as metadata.

IDDE currently has duplicate implementations of algorithms.

We used to instrument the algorithm implementation in the runtime so that it could be compiled to work either in- or out-of-process. The out-of-process library could be loaded as a gdb/dbx plugin. This certainly kept the debugger in sync with the runtime, but the instrumented runtime code was tricky to write.

**Comment by bnoordhuis** [comment] 2015-10-11 19:46
> the VM itself would ship with a debugger that looks just like the normal debugger API, but would support reading its state from a core file

How would that work?  The idea sounds intriguing but I don't imagine the V8 people are very eager to include an ELF or Mach-O parser and all the finicky stuff that comes with parsing core files.

> but requires more a lot more interest from the V8 team than I've seen up to this point.

Can you blame them?  What's in it for them?  Nothing, just more maintenance work.

**Comment by indutny** [comment] 2015-10-11 19:55
What do you think about reusing https://github.com/indutny/core2dump ? It has a DWARF parser, and works on both linux/mac. (Though, it is probably broken _right now_, because I wrote it for v0.12)

**Comment by bnoordhuis** [comment] 2015-10-11 20:23
@indutny What does it do?  The README is a little light on details.

**Comment by indutny** [comment] 2015-10-11 20:50
It takes core file, and extracts stack trace and/or heapdump out of it.

**Comment by indutny** [comment] 2015-10-11 20:56
Again, it is very likely broken at this point, but the fixes are very easy to do if we are interested in using this project.

**Comment by davepacheco** [comment] 2015-10-12 03:33
> > the VM itself would ship with a debugger that looks just like the normal debugger API, but would support reading its state from a core file
> 
> How would that work? The idea sounds intriguing but I don't imagine the V8 people are very eager to include an ELF or Mach-O parser and all the finicky stuff that comes with parsing core files.

We didn't get very far in designing it, but the details would be totally VM-dependent, and it's not clear it would be a native debugger at all.  The idea was to have an implementation of the debugger API (i.e., for JavaScript-level debugging) that would read VM structures from the core file rather than talk to a live VM.

> > but requires more a lot more interest from the V8 team than I've seen up to this point.
> 
> Can you blame them? What's in it for them? Nothing, just more maintenance work.

No, I don't blame them.  While I think there could be value for the V8 team in the ability to debug JavaScript code postmortem, they've obviously got other priorities, and that's their prerogative.  I was just explaining that the more integrated approach to building a postmortem debugger is not tenable for a group of engineers working entirely outside the core team, and that's why with mdb_v8 we took an approach that was intended to be as minimal a maintenance burden for the V8 team as I could envision (and I was grateful they accepted it).

**Comment by richardlau** [comment] 2018-08-15 16:47
Closing due to inactivity. If this work still needs to be tracked, please open a new issue over in https://github.com/nodejs/diagnostics.

**Closed as completed by richardlau** 2018-08-15 16:47 UTC
